language: node_js
node_js: 
  - "12"
addons:
  ssh_known_hosts:
  - 54.179.207.218
before_install:
- openssl aes-256-cbc -K $encrypted_ec0015db4ac4_key -iv $encrypted_ec0015db4ac4_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/.ssh/id_rsa
- ssh-add ~/.ssh/id_rsa
install: 
  - npm install
script: true
after_success:
  - ssh ubuntu@54.179.207.218 -o StrictHostKeyChecking=no 'cd ~ && pm2 reload all && touch test'