language: node_js
node_js: 
  - "12"
before_install:
  - openssl aes-256-cbc -K $encrypted_f0d2ff819631_key -iv $encrypted_f0d2ff819631_iv -in authorized_keys.enc -out ~\/.ssh/authorized_keys -d
install: 
  - npm install
script: true
after_success:
  - ssh ubuntu@54.179.207.218 'pm2 reload all'